/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(SnC_HierBlk.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(6891bd56a1f1051b375a47e0221531bb)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/tddModulePkg/SnC_HierBlk.h>
// pydoc.h is automatically generated in the build directory
#include <SnC_HierBlk_pydoc.h>

void bind_SnC_HierBlk(py::module& m)
{

    using SnC_HierBlk    = gr::tddModulePkg::SnC_HierBlk;


    py::class_<SnC_HierBlk, gr::hier_block2,
        std::shared_ptr<SnC_HierBlk>>(m, "SnC_HierBlk", D(SnC_HierBlk))

        .def(py::init(&SnC_HierBlk::make),
           D(SnC_HierBlk,make)
        )
        



        ;




}








