/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(SnCHier_Blk_NDiv.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(12c475409df4e44909478aaa02737908)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/tddModulePkg/SnCHier_Blk_NDiv.h>
// pydoc.h is automatically generated in the build directory
#include <SnCHier_Blk_NDiv_pydoc.h>

void bind_SnCHier_Blk_NDiv(py::module& m)
{

    using SnCHier_Blk_NDiv    = gr::tddModulePkg::SnCHier_Blk_NDiv;


    py::class_<SnCHier_Blk_NDiv, gr::hier_block2,
        std::shared_ptr<SnCHier_Blk_NDiv>>(m, "SnCHier_Blk_NDiv", D(SnCHier_Blk_NDiv))

        .def(py::init(&SnCHier_Blk_NDiv::make),
           D(SnCHier_Blk_NDiv,make)
        )
        



        ;




}








