/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(SnCHier_Blk_NSnH.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d4dcf958071fa0c63d9ade5634548573)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/tddModulePkg/SnCHier_Blk_NSnH.h>
// pydoc.h is automatically generated in the build directory
#include <SnCHier_Blk_NSnH_pydoc.h>

void bind_SnCHier_Blk_NSnH(py::module& m)
{

    using SnCHier_Blk_NSnH    = gr::tddModulePkg::SnCHier_Blk_NSnH;


    py::class_<SnCHier_Blk_NSnH, gr::hier_block2,
        std::shared_ptr<SnCHier_Blk_NSnH>>(m, "SnCHier_Blk_NSnH", D(SnCHier_Blk_NSnH))

        .def(py::init(&SnCHier_Blk_NSnH::make),
           D(SnCHier_Blk_NSnH,make)
        )
        



        ;




}








