/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(tddLatReadSink.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(7424f5d6c90004594059b9f5847291a5)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/tddModulePkg/tddLatReadSink.h>
// pydoc.h is automatically generated in the build directory
#include <tddLatReadSink_pydoc.h>

void bind_tddLatReadSink(py::module& m)
{

    using tddLatReadSink = ::gr::tddModulePkg::tddLatReadSink;


    py::class_<tddLatReadSink,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<tddLatReadSink>>(m, "tddLatReadSink", D(tddLatReadSink))

        .def(py::init(&tddLatReadSink::make),
             py::arg("item_size"),
             D(tddLatReadSink, make))


        ;
}
