/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(tddMessageStrobe.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(009f341605f914f03171394d2848006e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/tddModulePkg/tddMessageStrobe.h>
// pydoc.h is automatically generated in the build directory
#include <tddMessageStrobe_pydoc.h>

void bind_tddMessageStrobe(py::module& m)
{

    using tddMessageStrobe = ::gr::tddModulePkg::tddMessageStrobe;


    py::class_<tddMessageStrobe,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<tddMessageStrobe>>(
        m, "tddMessageStrobe", D(tddMessageStrobe))

        .def(py::init(&tddMessageStrobe::make),
             py::arg("itemsize"),
             py::arg("switch_interval") = 100.,
             py::arg("guard_time") = 10.,
             py::arg("st_mode") = 0,
             D(tddMessageStrobe, make))


        ;
}
