/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(tddOFDMCyclicPrefix.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(de38b2e61e410f70bf7a4073ec0783ed)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/tddModulePkg/tddOFDMCyclicPrefix.h>
// pydoc.h is automatically generated in the build directory
#include <tddOFDMCyclicPrefix_pydoc.h>

void bind_tddOFDMCyclicPrefix(py::module& m)
{

    using tddOFDMCyclicPrefix = ::gr::tddModulePkg::tddOFDMCyclicPrefix;


    py::class_<tddOFDMCyclicPrefix,
               gr::tagged_stream_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<tddOFDMCyclicPrefix>>(
        m, "tddOFDMCyclicPrefix", D(tddOFDMCyclicPrefix))

        .def(py::init(&tddOFDMCyclicPrefix::make),
             py::arg("fft_len"),
             py::arg("cp_lengths"),
             py::arg("rolloff_len") = 0,
             py::arg("len_tag_key") = "",
             D(tddOFDMCyclicPrefix, make))


        ;
}
