/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(tddRandomSrc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(b86d1fcae388d68de6278e734ec784c3)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/tddModulePkg/tddRandomSrc.h>
// pydoc.h is automatically generated in the build directory
#include <tddRandomSrc_pydoc.h>

void bind_tddRandomSrc(py::module& m)
{

    using tddRandomSrc = ::gr::tddModulePkg::tddRandomSrc;


    py::class_<tddRandomSrc,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<tddRandomSrc>>(m, "tddRandomSrc", D(tddRandomSrc))

        .def(py::init(&tddRandomSrc::make),
             py::arg("tx_time_interval") = 100.,
             py::arg("samples_per_sec") = 1000000,
             py::arg("pkt_len") = 1920,
             py::arg("mode") = 1,
             D(tddRandomSrc, make))


        ;
}
