/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(tddTaggedStreamMux.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f85b957050a0f5a6c917ad1b635e7413)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/tddModulePkg/tddTaggedStreamMux.h>
// pydoc.h is automatically generated in the build directory
#include <tddTaggedStreamMux_pydoc.h>

void bind_tddTaggedStreamMux(py::module& m)
{

    using tddTaggedStreamMux = ::gr::tddModulePkg::tddTaggedStreamMux;


    py::class_<tddTaggedStreamMux,
               gr::tagged_stream_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<tddTaggedStreamMux>>(
        m, "tddTaggedStreamMux", D(tddTaggedStreamMux))

        .def(py::init(&tddTaggedStreamMux::make),
             py::arg("itemsize"),
             py::arg("lengthtagname"),
             py::arg("tag_preserve_head_pos"),
             py::arg("header_len"),
             D(tddTaggedStreamMux, make))


        ;
}
