#log or plot
type_of_operation: plot
logfile_path: logi.log

perf_logger:
  #select between avg, inst, var or all
  val_type: all
  host: localhost
  port: 12345
  interval: 4 #set an interval to poll for values in sec

plotter:
  #to process the chain correctly from the logfile
  tx_or_rx: 0 #0-tx/1-rx, to create an edgelist for TDD
  edgelist_filepath: 0 #keep it 0 if no custom file is to be selected
  start_node: ["randomSrcTdd0","usrp_source"] #tx-startnode, rx-startnode, 
                                              #change it according to the name of the blocks
  #3d plots for latency vs time and buffer% vs time
  #2d plots for other plots across rest of the perf counters
  type: 2d
  #3d plot 
  #id - prints block ids on the x-axis of 3d graph
  #name - prints blk names instead
  xticks: id
  #plot buffer% vs time - 0
  #plot lat vs time - 1
  #plot total work vs time -2
  3dplot_type: 1
  #2d plots
  #avg, inst, var
  val_type: inst
  #1-to get a snapshot for all blks at the first looged timestamp
  #0-to get data for a specific blk across all timestamps
  all_blocks: 1
  #either give blk id or blk name to search & plot
  search_blk: 19 #eg. packet_headergenerator_bb_impl0 #43
