/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(1) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(latTagSink.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(8e088da38af42024464b808f0f46c1e9) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/tddModules/latTagSink.h>
// pydoc.h is automatically generated in the build directory
#include <latTagSink_pydoc.h>

void bind_latTagSink(py::module &m) {

  using latTagSink = ::gr::tddModules::latTagSink;

  py::class_<latTagSink, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<latTagSink>>(m, "latTagSink", D(latTagSink))

      .def(py::init(&latTagSink::make), py::arg("item_size"),
           D(latTagSink, make))

      ;
}
