/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(msgStrobeTddRx.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(3306940f2b9611f96adb0b7ba697332e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/tddModules/msgStrobeTddRx.h>
// pydoc.h is automatically generated in the build directory
#include <msgStrobeTddRx_pydoc.h>

void bind_msgStrobeTddRx(py::module& m)
{

    using msgStrobeTddRx    = gr::tddModules::msgStrobeTddRx;


    py::class_<msgStrobeTddRx, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<msgStrobeTddRx>>(m, "msgStrobeTddRx", D(msgStrobeTddRx))

        .def(py::init(&msgStrobeTddRx::make),
           D(msgStrobeTddRx,make)
        )
        



        ;




}








