/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(nullSrcLat.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(321b439e55f7356c5bc3e520797637a5)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/tddModules/nullSrcLat.h>
// pydoc.h is automatically generated in the build directory
#include <nullSrcLat_pydoc.h>

void bind_nullSrcLat(py::module& m)
{

    using nullSrcLat    = gr::tddModules::nullSrcLat;


    py::class_<nullSrcLat, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<nullSrcLat>>(m, "nullSrcLat", D(nullSrcLat))

        .def(py::init(&nullSrcLat::make),
           D(nullSrcLat,make)
        )
        



        ;




}








