/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(randomSrcTdd.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(5b726585f1920e00bfec541095d41bcc)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/tddModules/randomSrcTdd.h>
// pydoc.h is automatically generated in the build directory
#include <randomSrcTdd_pydoc.h>

void bind_randomSrcTdd(py::module& m)
{

    using randomSrcTdd = ::gr::tddModules::randomSrcTdd;


    py::class_<randomSrcTdd,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<randomSrcTdd>>(m, "randomSrcTdd", D(randomSrcTdd))

        .def(py::init(&randomSrcTdd::make),
             py::arg("tx_time_interval") = 1.,
             py::arg("samples_per_sec") = 1000000,
             py::arg("pkt_len") = 1920,
             py::arg("mode") = 1,
             D(randomSrcTdd, make))


        ;
}
