/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(tdd_ofdm_cyclic_prefixer.h) */
/* BINDTOOL_HEADER_FILE_HASH(c56ea3f38a9a420e9b80828e9f73c3de) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/tddModules/tdd_ofdm_cyclic_prefixer.h>
// pydoc.h is automatically generated in the build directory
#include <tdd_ofdm_cyclic_prefixer_pydoc.h>

void bind_tdd_ofdm_cyclic_prefixer(py::module &m) {

  using tdd_ofdm_cyclic_prefixer = ::gr::tddModules::tdd_ofdm_cyclic_prefixer;

  py::class_<tdd_ofdm_cyclic_prefixer, gr::tagged_stream_block, gr::block,
             gr::basic_block, std::shared_ptr<tdd_ofdm_cyclic_prefixer>>(
      m, "tdd_ofdm_cyclic_prefixer", D(tdd_ofdm_cyclic_prefixer))

      .def(py::init(&tdd_ofdm_cyclic_prefixer::make), py::arg("fft_len"),
           py::arg("cp_lengths"), py::arg("rolloff_len") = 0,
           py::arg("len_tag_key") = "", D(tdd_ofdm_cyclic_prefixer, make))

      ;
}
