/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(tddTagStreamMux.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(6d328ea72e05a5a5aff93f3e450328c7)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/tddModules/tddTagStreamMux.h>
// pydoc.h is automatically generated in the build directory
#include <tddTagStreamMux_pydoc.h>

void bind_tddTagStreamMux(py::module& m)
{

    using tddTagStreamMux = ::gr::tddModules::tddTagStreamMux;


    py::class_<tddTagStreamMux,
               gr::tagged_stream_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<tddTagStreamMux>>(m, "tddTagStreamMux", D(tddTagStreamMux))

        .def(py::init(&tddTagStreamMux::make),
             py::arg("itemsize"),
             py::arg("lengthtagname"),
             py::arg("tag_preserve_head_pos"),
             py::arg("header_len"),
             D(tddTagStreamMux, make))


        ;
}
